# Outputs for the RDS Module
# These outputs expose the RDS instance details and related resources

output "db_instance_id" {
  description = "The RDS instance identifier"
  value       = aws_db_instance.main.id
}

output "db_instance_address" {
  description = "The address of the RDS instance"
  value       = aws_db_instance.main.address
}

output "db_instance_endpoint" {
  description = "The connection endpoint of the RDS instance"
  value       = aws_db_instance.main.endpoint
}

output "db_instance_arn" {
  description = "The ARN of the RDS instance"
  value       = aws_db_instance.main.arn
}

output "db_instance_name" {
  description = "The database name"
  value       = aws_db_instance.main.db_name
}

output "db_instance_username" {
  description = "The master username for the database"
  value       = aws_db_instance.main.username
}

output "db_instance_port" {
  description = "The database port"
  value       = aws_db_instance.main.port
}

output "db_subnet_group_id" {
  description = "The ID of the DB subnet group"
  value       = var.use_existing_subnet_group ? var.existing_subnet_group_name : aws_db_subnet_group.main[0].id
}

output "db_subnet_group_name" {
  description = "The name of the DB subnet group"
  value       = var.use_existing_subnet_group ? var.existing_subnet_group_name : aws_db_subnet_group.main[0].name
}

output "db_parameter_group_id" {
  description = "The ID of the DB parameter group"
  value       = aws_db_parameter_group.main.id
}

output "db_parameter_group_name" {
  description = "The name of the DB parameter group"
  value       = aws_db_parameter_group.main.name
}

output "db_security_group_id" {
  description = "The ID of the security group for the RDS instance"
  value       = aws_security_group.db.id
}

output "db_instance_password" {
  description = "The database password (only if generated by the module)"
  value       = var.password == "" ? random_password.db_password[0].result : null
  sensitive   = true
}

output "db_replica_id" {
  description = "The RDS replica instance identifier"
  value       = var.create_replica ? aws_db_instance.replica[0].id : ""
}

output "db_replica_address" {
  description = "The address of the RDS replica instance"
  value       = var.create_replica ? aws_db_instance.replica[0].address : ""
}

output "db_replica_endpoint" {
  description = "The connection endpoint of the RDS replica instance"
  value       = var.create_replica ? aws_db_instance.replica[0].endpoint : ""
}

output "db_replica_arn" {
  description = "The ARN of the RDS replica instance"
  value       = var.create_replica ? aws_db_instance.replica[0].arn : ""
}

output "cloudwatch_alarm_arns" {
  description = "List of ARNs of CloudWatch alarms created for the RDS instance"
  value       = var.create_cloudwatch_alarms ? concat(
    [aws_cloudwatch_metric_alarm.cpu_utilization_too_high[0].arn],
    [aws_cloudwatch_metric_alarm.free_storage_space_too_low[0].arn],
    [aws_cloudwatch_metric_alarm.free_memory_too_low[0].arn],
    [aws_cloudwatch_metric_alarm.high_connection_count[0].arn]
  ) : []
}