version: '3.8'

services:
  web:
    image: loan_management_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DB_HOST=db
      - DB_NAME=loan_management_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=loan_management_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: loan_management_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DB_HOST=db
      - DB_NAME=loan_management_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    image: loan_management_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DB_HOST=db
      - DB_NAME=loan_management_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: loan_management_network